# Generated by Django 2.1.4 on 2019-04-12 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='targetfield',
            new_name='target',
        ),
    ]
