# Generated by Django 2.2 on 2019-04-19 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_auto_20190412_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='errors',
            new_name='scores',
        ),
    ]
