# Generated by Django 2.2 on 2019-04-19 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0004_auto_20190419_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auto.Document'),
        ),
    ]
